apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  namespace: istio-tracing
  labels:
    app: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - name: recommendation
        image: gcr.io/cirrus-initial-project/recommendation:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: istio-tracing
  labels:
    app: recommendation    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendation
  type: LoadBalancer
